apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jen4vuzk3-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:13b8512eb3276369d2b0716043deb7f2f3f451cd@sha256:7ba0303e83d08ea25cbaadc547ba2bf2c5ae8a5c30088f023b57133c5b8c0a71
          name: container-image
